-- AlterTable
ALTER TABLE `jobapplied` ADD COLUMN `appliedDate` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    ADD COLUMN `status` ENUM('IN_PROGRESS', 'RESUMED_REVIEWED', 'SHORTLISTED', 'INTERVIEW_SCHEDULED', 'REJECTED') NOT NULL DEFAULT 'IN_PROGRESS';
